apiVersion: v1
kind: Service
metadata:
  name: keyvalue-redis-master 
  labels:
    app: keyvalue-redis-master
#  annotations:
#    dns.alpha.kubernetes.io/external: redis.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: redis-native 
    port: 6379
    targetPort: 6379
  - name: webdis-native
    port: 7379
    targetPort: 7379
  selector:
    app: keyvalue-redis-master

