apiVersion: v1
kind: ReplicationController
metadata:
  name: keyvalue-redis-master
  labels:
    app: keyvalue-redis-master
spec:
  replicas: 1
  selector:
    name: keyvalue-redis-master
  template:
    metadata:
      labels:
        name: keyvalue-redis-master
    spec:
      containers:
      - name: keyvalue-redis-master
        image: docker.io/fluxcapacitor/keyvalue-redis-master:master
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 6379
        - containerPort: 7379
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "master"
