apiVersion: v1
kind: ReplicationController
metadata:
  name: sql-mysql-master
  labels:
    app: sql-mysql-master
spec:
  replicas: 1
  selector:
    name: sql-mysql-master
  template:
    metadata:
      labels:
        name: sql-mysql-master
    spec:
      containers:
      - name: sql-mysql-master
        image: docker.io/fluxcapacitor/sql-mysql-master:master
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 3306
