apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper 
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: docker.io/fluxcapacitor/zookeeper:master
        resources:
          limits:
            cpu: 1000m
            memory: 5000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - containerPort: 2181
        volumeMounts:
          - name: kube-config-secret-volume
            readOnly: true
            mountPath: /root/.kube
          - name: hadoop-conf-dev-volume
            mountPath: /etc/hadoop/conf
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: kube-config-secret-volume
          secret:
            secretName: kube-config-secret
        - name: hadoop-conf-dev-volume
          secret:
            secretName: hadoop-conf-dev
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml"
            revision: "master"
      imagePullSecrets:
        - name: githubsshkey
