apiVersion: v1
kind: ReplicationController
metadata:
  name: scheduler-airflow
  labels:
    app: scheduler-airflow
spec:
  replicas: 1
  selector:
    name: scheduler-airflow
  template:
    metadata:
      labels:
        name: scheduler-airflow
    spec:
      containers:

      - name: airflow
        image: eu.gcr.io/ds-platform-qa/scheduler-airflow
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://apachespark-master-2-1-0:7077
        - name: SPARK_SUBMIT_ARGS
          value: ""
        - name: GIT_USER
          valueFrom:
           secretKeyRef:
            name: shareactor-secrets
            key: GIT_USER
        - name: GIT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: shareactor-secrets
            key: GIT_PASSWORD
        ports:
        - containerPort: 8080
        - containerPort: 5000
        - containerPort: 5555
        - containerPort: 8793
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: kube-config-secret-volume
            readOnly: true
            mountPath: /root/.kube
          - name: git-volume
            mountPath: /root/volumes
        securityContext:
          privileged: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - name: git-volume
          gitRepo:
            repository: "https://[o-auth-personal-acess-token]:[x-oauth-basic]@github.com/shareactorIO/source.ml.git"
            revision: "master"
        - name: kube-config-secret-volume
          secret:
            secretName: kube-config-secret
