apiVersion: v1
kind: ReplicationController
metadata:
  name: prediction-java
  labels:
    app: prediction-java
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    name: prediction-java
  template:
    metadata:
      labels:
        name: prediction-java
        hystrix.enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "9040"
    spec:
      containers:
      - name: prediction-java
        image: docker.io/fluxcapacitor/prediction-java:master
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 9040
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/fluxcapacitor/source.ml.git"
            revision: "master"
