apiVersion: v1
kind: Service
metadata:
  name: prediction-java
  labels:
    hystrix.enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-java
    port: 80 
    targetPort: 9040 
  selector:
    name: prediction-java
    hystrix.enabled: "true" 
