apiVersion: v1
kind: Service
metadata:
  name: prediction-jvm
  labels:
    app: prediction-jvm
    hystrix.enabled: "true"
#    dns: route53
#  annotations:
#    domainName: "prediction-jvm.your.domain.com"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-jvm
    port: 80 
    targetPort: 9040 
  selector:
    app: prediction-jvm
    hystrix.enabled: "true" 
