apiVersion: v1
kind: ReplicationController
metadata:
  name: prediction-pmml-canary
  labels:
    app: prediction-pmml
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    name: prediction-pmml-canary
  template:
    metadata:
      labels:
        name: prediction-pmml-canary
        hystrix.enabled: "true"
    spec:
      containers:
      - name: prediction-pmml-canary
        image: docker.io/fluxcapacitor/prediction-pmml:canary
        imagePullPolicy: "Always"
        env:
        ports:
        - containerPort: 9040
      nodeSelector:
        prediction: "true"
#        livenessProbe:
#          httpGet:
#            path: "/health"
#            port: 9040
#          initialDelaySeconds: 300
#        readinessProbe:
#          httpGet:
#            path: "/health"
#            port: 9040
#          initialDelaySeconds: 30
