apiVersion: v1
kind: Service
metadata:
  name: prediction-spark
  labels:
    hystrix.enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-spark
    port: 80 
    targetPort: 9040
  selector:
    name: prediction-spark
    hystrix.enabled: "true"
