apiVersion: v1
kind: Service
metadata:
  name: prediction-tensorflow-gpu
  labels:
    hystrix.enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: prediction-tensorflow-gpu
    port: 80 
    targetPort: 9040
  selector:
    name: prediction-tensorflow-gpu
    hystrix.enabled: "true"
