apiVersion: v1
kind: ReplicationController
metadata:
  name: metastore-2-1-1
  labels:
    app: metastore
    version: 2.1.1
spec:
  replicas: 1
  selector:
    name: metastore-2-1-1
  template:
    metadata:
      labels:
        name: metastore-2-1-1
    spec:
      containers:
      - name: metastore-2-1-1
        image: docker.io/fluxcapacitor/metastore-2.1.1:master
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 9083
      nodeSelector:
        training: "true"
