apiVersion: v1
kind: ReplicationController
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
spec:
  replicas: 1
  selector:
    name: hdfs-namenode
  template:
    metadata:
      labels:
        name: hdfs-namemode
    spec:
      containers:
      - name: hdfs-namenode
        image: docker.io/fluxcapacitor/hdfs-namenode:master
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 8000
        - containerPort: 9000
        - containerPort: 50070
