apiVersion: v1
kind: Service
metadata:
  name: web-home 
  labels:
    app: web-home
#  annotations:
#    dns.alpha.kubernetes.io/external: www.your.domain.com
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: web-home
