apiVersion: v1
kind: Service
metadata:
  name: zeppelin
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80 
    targetPort: 3123 
  - name: "websocket"
    port: 81 
    targetPort: 3124
  selector:
    name: zeppelin
