apiVersion: v1
kind: ReplicationController
metadata:
  name: zeppelin
  labels:
    app: zeppelin
spec:
  replicas: 1
  selector:
    name: zeppelin
  template:
    metadata:
      labels:
        name: zeppelin
    spec:
      containers:
      - name: zeppelin
        image: docker.io/fluxcapacitor/zeppelin:master
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://apachespark-master-2-1-0:7077
        - name: SPARK_SUBMIT_ARGS
          value: "--conf spark.cores.max=2 --conf spark.executor.memory=2g --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.1 --jars /root/lib/jpmml-sparkml-package-1.0-SNAPSHOT.jar --py-files /root/lib/jpmml.py"
        ports:
        - containerPort: 3123
        - containerPort: 3124
        volumeMounts:
          - name: git-volume
            mountPath: /root/volumes
      volumes:
        - name: git-volume
          gitRepo:
            repository: "https://github.com/shareactorIO/source.ml.git"
            revision: "master"
