apiVersion: v1
kind: ReplicationController
metadata:
  name: apachespark-worker-2-1-0
  labels:
    name: apachespark-worker-2-1-0
spec:
  replicas: 1
  selector:
    name: apachespark-worker-2-1-0
  template:
    metadata:
      labels:
        name: apachespark-worker-2-1-0
    spec:
      containers:
      - name: apachespark-worker-2-1-0
        image: docker.io/fluxcapacitor/apachespark-worker-2.1.0:master
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_WORKER_CORES
          value: "4"
        - name: SPARK_WORKER_MEMORY
          value: 4g
        - name: SPARK_MASTER
          value: spark://apachespark-master-2-1-0:7077
        ports:
        - containerPort: 6061
