apiVersion: v1
kind: Service
metadata:
  name: apachespark-worker-2-1-0
spec:
  type: LoadBalancer
  ports:
  - name: admin-http
    port: 80
    targetPort: 6061
  selector:
    name: apachespark-worker-2-1-0
